name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the Node.js version your project requires

      - name: Install dependencies
        run: npm install
        working-directory: my-app/backend/frontend # Ensure this path is correct

      - name: Build the project
        run: npm run build
        working-directory: my-app/backend/frontend # Ensure this path is correct

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_ISLAND_0C92A8610 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # This is automatically provided by GitHub
          action: 'upload'
          app_location: 'my-app/backend/frontend/build' # Ensure this path is correct
          api_location: 'api' # Location of your Azure Functions code (if any)
          output_location: 'build' # Location of the build output directory